### ISSUE TITLE
AdapterError: no pop found for pre / post cell type

### ISSUE THREAD

**Issue by danilobenozzo** [dbbs-lab/bsb-neuron#16]
https://github.com/dbbs-lab/bsb-neuron/blob/6f9e5114e6dbad3010cb3a9c6750fc1089e83a3f/bsb_neuron/connection.py#L61C13-L61C71
@Helveg does this mean that each `simdata` must have at least one pre and post cell for each `ConnectivitySet`?
If this is a requirement, it doesn't seem to be the case with small chunks split across many cores.

**Comment by Helveg** [comment]
It should at least contain an empty `Population` for that cell type.

**Comment by danilobenozzo** [comment]
Is this the correct way to create an empty `Population` of `cell_model`
`simdata.populations[cell_model] = NeuronPopulation(cell_model, [])` ?

**Comment by Helveg** [comment]
I think so, yes
