### ISSUE TITLE
Shape incompatibility

### ISSUE THREAD

**Issue by danilobenozzo** [dbbs-lab/bsb-neuron#18]
https://github.com/dbbs-lab/bsb-core/blob/88a59966e12c13a0ef192e87c64bbe0f4f589e7e/bsb/simulation/targetting.py#L229C26-L229C67

`simdata.placement[model].load_positions()` loads the positions of all cell `model` while `simdata.populations[model]` refers to only the subset of cells in `simdata.chunks` (at least in bsb_neuron).
Shouldn't it be `simulation.cell_models.get(model.name).get_placement_set(chunks=simdata.chunks).load_positions()` instead?

**Comment by Helveg** [comment]
I think this is a `bsb-neuron` issue? And yes, perhaps we can add it to: https://github.com/dbbs-lab/bsb-core/blob/88a59966e12c13a0ef192e87c64bbe0f4f589e7e/bsb/simulation/adapter.py#L48-L54

so that all the placement sets in the `.placement` attribute are already set to those chunks?

**Comment by filimarc** [comment]
Uhm, the changes i made are wrong. The fact is that at this point ( https://github.com/dbbs-lab/bsb-core/blob/88a59966e12c13a0ef192e87c64bbe0f4f589e7e/bsb/simulation/adapter.py#L48-L54) we are not aware of the chunks we are in. Maybe we can upload the `.placement` restricted to chunks in the NeuronAdapter
